name: List installed PS modules

on: [workflow_dispatch]

jobs:
  build:
    name: run command
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: command
        run: Get-Module -ListAvailable
        shell: pwsh
