name: (dry run) test and build

on:
  pull_request:
    branches:
      - dev

# on: workflow_dispatch

jobs:
  build:
    name: test and build PowerShell module
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: lint with PSScriptAnalyzer
      run: ./build/lint.ps1 -Path "./"
      shell: pwsh

    - name: install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.1
      with:
        versionSpec: '6.0.x'

    - name: determine next release version
      uses: gittools/actions/gitversion/execute@v3.1.1

    - name: output version
      run: |
        echo "Ver: ${{env.majorMinorPatch}} PreReleaseTag: ${{env.preReleaseTag}}"

    - name: build module
      run: ./build/build.ps1 -Version ${{env.majorMinorPatch}}
      shell: pwsh
