name: Test-PSModule

on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main", "dev" ]


jobs:
  Test-PSModule:
    name: Test-PSModule
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Initialize environment
        uses: PSModule/Initialize-PSModule@main

      - name: Test-PSModule
        uses: PSModule/Test-PSModule@main
        with:
          Path: src
          TestType: SourceCode
